### ISSUE TITLE
freelancer-jekyll-theme: installation problem 

### ISSUE THREAD

**Issue by EdicRC** [jeromelachaud/freelancer-theme#102]
I have just installed jekyll-theme freelancer into my local folder  c://edicrc/freelancer-theme but there is a problem 

My step:
1. download freelancer-jekyll-theme
2. Run command  "jekyll serve"
3.  This message appears 
"$ jekyll serve
fatal: not a git repository (or any of the parent directories): .git
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/resolver.rb:287:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'rake (~> 10.0) x64-mingw32' in any of the gem sources listed in your Gemfile. (Bundler::GemNotFound)
...etc 
"
any ideas why?

**Comment by iamchrisb** [comment]
hey there! I just ran into the same issue like you. I am not very familiar with the ruby, gem environment but I gave it a shot. I am working on a win10 system (what always feels like a crime as a dev :D but nevermind) I did the following steps to fix the error: 

1. reinstalled the ruby-env (with MYSYS2 marked to be installed also, seems like I forgot that with the first install) something similar like this: https://jekyll-windows.juthilo.com/1-ruby-and-devkit/ 

2. I updated the gem file of the github projekt (freelancer-theme-jekyll.gemspec) with the following versions: 
spec.add_development_dependency "bundler", "~> 2.0" (from 1.12)
spec.add_development_dependency "rake", "~> 12.3.0" (from 10.0)
3. I reinstalled the bundle with: "bundle install"
4. I used the bundle exec to let jekyll serve the stuff: "bundle exec jekyll serve"

You could may try step 2-4 in the first place before you update your ruby installation. I hope it helps.

**Comment by jeromelachaud** [comment]
https://github.com/jeromelachaud/freelancer-theme/pull/103
