### ISSUE TITLE
gemspec requires old bundler

### ISSUE THREAD

**Issue by antgel** [jeromelachaud/freelancer-theme#106]
Current bundler is 2.x, however `freelancer-theme-jekyll.gemspec` contains `spec.add_development_dependency "bundler", "~> 1.12"`.

I hacked around it for now by removing the version requirement. (I'd have submitted a PR if I knew what the intended behaviour was.)

**Comment by jeromelachaud** [comment]
https://github.com/jeromelachaud/freelancer-theme/pull/103
