### ISSUE TITLE
Support Jekyll 4.0

### ISSUE THREAD

**Issue by cianiandreadev** [jeromelachaud/freelancer-theme#109]
Dear all,

I am new to Jekyll and I would really love to use this theme.
Is there planned the support for Jekyll 4.x?

Thanks in advance 🙂

**Comment by jeromelachaud** [comment]
Hi, 
I don't know how much work this requires but I don't have the bandwidth to investigate it now.
Sorry

**Comment by jeromelachaud** [comment]
in fact, there was a open PR for that. It's merged now.
