### ISSUE TITLE
Invalid Date: '' is not a valid datetime. Liquid Exception: exit in feed.xml

### ISSUE THREAD

**Issue by johnasp** [jeromelachaud/freelancer-theme#111]
I've cloned the latest build today and get **Invalid Date: '' is not a valid datetime.** when I run either serve or build commands.

I deleted the file called feed.xml anf the the build then ran.   Obviouslly a problem in that file somewhere.  Anyone know where?

**Comment by johnasp** [comment]
So I removed this whole line 43 and it worked.  

`<updated>{{ post.last_modified_at | default: post.date | date_to_xmlschema }}</updated>`

Something to do with the post.date variable I guess.  Ill dig into this more when I get a minute.

**Comment by jeromelachaud** [comment]
I cannot reproduce the issue. What's your environment?
