### ISSUE TITLE
html-proofer dependency issue

### ISSUE THREAD

**Issue by gwilku** [jeromelachaud/freelancer-theme#118]
**Describe the bug**
`jekyll serve` in the theme folder (downloaded as is) throws the following error:

> C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler.rb:634:in `rescue in eval_gemspec':  (Bundler::Dsl::DSLError)
> [!] There was an error parsing `Gemfile`:
> [!] There was an error while loading `freelancer-theme-jekyll.gemspec`: No such file or directory - git ls-files -z. Bundler cannot continue.
> 
>  #  from E:/GitHub/freelancer-theme/freelancer-theme-jekyll.gemspec:14
>  #  -------------------------------------------
>  #    spec.add_development_dependency "html-proofer", "~> 3.15"
>  >  end #  # coding: utf-8
>  #  -------------------------------------------
> . Bundler cannot continue.

**Expected behavior**
I'd like to see the theme served. I'm guessing it has to do with the proofer, but after some trial and error I don't think it's the dependency, but rather "No such file or directory - git ls-files -z. " this part throwing an error.

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser n/a
-  Ruby version 2.6.4

**Comment by sgarciav** [comment]
Created a PR to add the `html-proofer` dependency #164 .
