### ISSUE TITLE
Email form not working

### ISSUE THREAD

**Issue by Dwite** [jeromelachaud/freelancer-theme#14]
I'm getting "Sorry %username%, it seems that my mail server is not responding. Please try again later!" error all the time. Here is my code https://github.com/jeromelachaud/freelancer-theme/blob/master/_includes/contact_static.html , I used version of theme from gh-pages branch, maybe that's the reason? And is it possible to use master theme to host via github pages?

**Comment by jeromelachaud** [comment]
Hi, you should checkout the master branch.

**Comment by coenroest** [comment]
I do use the master branch but it has the same issue..
Anything that I missed?

**Comment by fkromer** [comment]
I observe the same behaviour like @Dwite when I use the php email functionality of the current master branch.

When I use the formspree email functionality of the current master branch instead with my email address I do not receive any emails... no formspree.io validation email at all!?

				<form  action="//formspree.io/thinwybk@mailbox.org" method="POST" name="sentMessage" id="contactForm" novalidate>
                                ...
				</form>
