### ISSUE TITLE
Linkedin icon in link

### ISSUE THREAD

**Issue by H-Eggels** [jeromelachaud/freelancer-theme#151]
Thank you for this great theme, it was exactly what I was looking for! It works great (even for a beginner like me). The only problem I have is that I can't get the Linkedin icon in the Linkedin button (witch works!) I changed the _config.yml as follows:
social:
#  - title: twitter
#    url: http://twitter.com/jekyllrb
  - title: Linkedin
    url: https://www.linkedin.com/in/aaaaaaa
What I'm doing wrong?
I installed the zip-flile at my provider who supports Jekyll-compatible sites (see link below)
https://soverin.net/help/docs/editor/

**Comment by agardnerIT** [comment]
It needs to match the [font awesome brands code](https://fontawesome.com/search?o=r&f=brands) exactly. So `linkedin` (lowercase)

```
social:
  - title: linkedin
    url: https://linkedin.com/...
```
