### ISSUE TITLE
_config.yml, description and meta_author not working

### ISSUE THREAD

**Issue by Swepz** [jeromelachaud/freelancer-theme#155]
**Describe the bug**
Trying to changed the description and meta_author, but when trying to share the link it still shows the template description and "First Lastname".

Before
```_config.yml
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
meta_author: LastName FirstName
```

After 

```_config.yml
description: "Foo Bar Baz"
meta_author: foo bar
```

1. Edit description and meta_author in _config.yml
2. Push to github to update gh-pages
3. Wait for Actions to update site
4. Open the website xxx.github.io
5. Share the link to Telegram or any app what shows meta_data

**Expected behavior**
Changed description and will show new description.

**Screenshots**
<img width="514" alt="Screenshot 2022-12-15 at 09 56 34" src="https://user-images.githubusercontent.com/32343381/207816208-b1af88d0-723f-455e-a848-94effe4f9751.png">

**Desktop (please complete the following information):**
 - OS: MacOS Montery 12.6  
 - Browser: Brave [Version 1.46.140 Chromium: 108.0.5359.99 (Official Build) (arm64)](https://brave.com/latest/)
-  Ruby version: ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.arm64e-darwin21]

**Comment by leabs** [comment]
I just tried this and the description and author updated fine in the head for me. If you can, force gh-pages to redeploy and force a hard refresh in your browser to make sure the old head info isn't cached or something

**Comment by Swepz** [comment]
That would definitely work, thanks. In my case, I believe that Telegram Cached the URL and meta data if I remember correctly.
