### ISSUE TITLE
remove header section?

### ISSUE THREAD

**Issue by LucaMoiana** [jeromelachaud/freelancer-theme#18]
Love this template, and I'd like to use it for my project page; so I want to remove the header section, did some test with no luck.

thanns

**Comment by jeromelachaud** [comment]
Hi there,

In the /_layouts/default.html file, comment the line #6 : {% include header.html %}

**Comment by LucaMoiana** [comment]
thanks for the fast reply; Following your instruction dough, I get Portfolio title attached to the navbar and the navbar as a bigger size then in about or contact.
How can I fix it?

**Comment by jeromelachaud** [comment]
Please, post a link or a screen grab of what you currently have and a jpg showing what you would like to achieve.
Thx

**Comment by LucaMoiana** [comment]
here is a screenshot: https://www.dropbox.com/s/yox838o0mh292r8/grab.tiff?dl=0

**Comment by jeromelachaud** [comment]
Hi Luca, sorry for the late reply.
I cannot reproduce the issue, see there : 
https://www.dropbox.com/s/jr92z04e0a1mw2l/freelancer-theme-noHeader.PNG?dl=0
Which browser are your using?
