### ISSUE TITLE
a way to optimize

### ISSUE THREAD

**Issue by gufoman88** [jeromelachaud/freelancer-theme#20]
I use this theme for my personal site. Then i try to analyze with google pagespeed and there is a way to optimize the site. You can find here the suggestion https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fjeromelachaud.github.io%2Ffreelancer-theme%2F&tab=mobile 
The most relevant problem is with CSS. There is a way to have the same result without CSS?

**Comment by jeromelachaud** [comment]
Hi there, 
Critical-path CSS could certainly be improved but I am not sure to get what you mean by "same result without CSS"...
Jerome

**Comment by gufoman88** [comment]
I mean the same graphic, the same font ( i have see that the problem is with google font) without css.

**Comment by pdostal** [comment]
@gufoman88 it is totally impossible :x:

**Comment by jeromelachaud** [comment]
@gufoman88 Modern web pages cannot live without CSS files. All of the design (ie colors, layout, font, etc.) are declared within those files.
