### ISSUE TITLE
CSS and JS files work fine on locahost, when pushed to gh-pages no css is rendered

### ISSUE THREAD

**Issue by tgaeta** [jeromelachaud/freelancer-theme#26]
I can't seem to get your theme working on gh-pages. It works fine locally, but once pushed to gh-pages, all styling is gone.

Any ideas? Did I miss a few steps to deploying to gh-pages?

**Comment by tgaeta** [comment]
Figured out some files contained forward slashes `/` that would break the loading of css and js files.

**Comment by jeromelachaud** [comment]
All right, feel free to open a PR so everyone could benefit from your fix ;-)

**Comment by tgaeta** [comment]
Here you go partner: PR https://github.com/jeromelachaud/freelancer-theme/pull/27 ;-)
