### ISSUE TITLE
Demo page isn't loading CSS or JS 

### ISSUE THREAD

**Issue by tgaeta** [jeromelachaud/freelancer-theme#30]
[Demo](http://jeromelachaud.github.io/freelancer-theme/) page is not loading the CSS for some reason.

![screen shot 2015-09-03 at 7 12 20 pm](https://cloud.githubusercontent.com/assets/9040988/9673205/d3e166cc-526f-11e5-80f7-71ec65b22018.png)

This most likely is related to PR https://github.com/jeromelachaud/freelancer-theme/pull/28.

**Comment by swethmandava** [comment]
I still have this problem. When I fork, I cant see these changes made. When I manually remove / from before css and js it still doesn't work
