### ISSUE TITLE
btn-success primary color not retrieved from _config yaml

### ISSUE THREAD

**Issue by jmr0** [jeromelachaud/freelancer-theme#38]
I noticed while customizing my template that class btn-success will not pull the colors defined in _config.yml, since bootstrap.min.css has these defined:

background-color:#128f76;border-color:#11866f

I was thinking of changing it to this for my purposes:

background-color:#{{site.color.primary-dark}};border-color:#{{site.color.primary}} 

And defining primary-dark in _config.yml

Happy to submit a pull request for it if interested (should I modify bootstrap.min.css directly?)

Thanks

**Comment by jeromelachaud** [comment]
Hi, you wouldn't want to change the bootstrap file because it is a third-party library and if I need to update it, your modification will be lost.
You would rather overwrite the btn-succcess class by adding its declaration in the main.css.
I would not accept a PR for that though.
Cheers
