### ISSUE TITLE
Adding social icon for Medium 

### ISSUE THREAD

**Issue by gtokman** [jeromelachaud/freelancer-theme#44]
Hey,

I am really enjoying the new theme. I add Medium to the social "around the web" footer. It navigates to the website correctly but the icon is missing. I cannot seem to find the place to add a social icon. 
Any help would be much appreciated!

Thanks

**Comment by igorPhelype** [comment]
Maybe you should try to update your font awesome css archive or you can simply use "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.2/css/font-awesome.min.css" on the href:
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.2/css/font-awesome.min.css" rel="stylesheet">

I tried it and the Medium icon appeared on your github portifolium site.

**Comment by igorPhelype** [comment]
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.2/css/font-awesome.min.css" rel="stylesheet">
<a href="https://medium.com/@GaryTokman" class="btn-social btn-outline"><i class="fa fa-medium"></i></a>

**Comment by igorPhelype** [comment]
The CDN content is updated constantly, but you may lose network performance loading this css from another location or you will be "hostage" of the cdn server.
So i guess it's better just to update your font-awesome.min.css local file.
