### ISSUE TITLE
Layout Broken Due to Missing Files

### ISSUE THREAD

**Issue by LiamInJapan** [jeromelachaud/freelancer-theme#48]
Hi there,

I just loaded up my portfolio to find the layout very broken due to missing files:

Screenshot:
<img width="1440" alt="screen shot 2016-07-01 at 09 12 48" src="https://cloud.githubusercontent.com/assets/1658103/16508233/089f8bde-3f6c-11e6-9ef7-cf70717115a9.png">

Errors:
<img width="456" alt="screen shot 2016-07-01 at 09 13 56" src="https://cloud.githubusercontent.com/assets/1658103/16508250/2fa92adc-3f6c-11e6-8e3a-6aa7aa491a7d.png">

It seems the server-side css and js files have been moved, breaking the layout. I have fixed it easily by pointing to alternative versions of these files in other locations in head.html but I recommend that you point to canonical/official versions of the files so layouts don't break every time files are moved.

**Comment by LiamInJapan** [comment]
e.g.

main.html
`"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"` 
`//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css`

javascript.html
`https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0/jquery.js`
`https://cdnjs.cloudflare.com/ajax/libs/classie/1.0.1/classie.js`
`https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js`

I can't for the life of me find an alternative location for:
http://sbootstrap-freelancer.startbootstrapc.netdna-cdn.com/js/cbpAnimatedHeader.js

**Comment by jeromelachaud** [comment]
Hi, all the needed js/css files are included in the repo.

**Comment by LiamInJapan** [comment]
True, but the code refers to externally hosted versions, which broke when they were moved (or I think this is what happened - I woke up to find my working blog not working for some external reason)

I've (mo
