### ISSUE TITLE
Help me  for installation

### ISSUE THREAD

**Issue by dexcycarol** [jeromelachaud/freelancer-theme#50]
could help as I can install this theme, I'm learning boostrap. I uploaded the template however achievement not link the page with the domain

**Comment by kkeertipati** [comment]
I need the same thing. Please help us

**Comment by kkeertipati** [comment]
Go to https://startbootstrap.com/template-overviews/freelancer/
search for download theme icon... and click and download it.
copy entire thing in web hosting in the folder containing index.html.
