### ISSUE TITLE
Social networks usernames 

### ISSUE THREAD

**Issue by StackTier** [jeromelachaud/freelancer-theme#57]
What specific Social networks are available? Thank you

**Comment by jeromelachaud** [comment]
https://github.com/jeromelachaud/freelancer-theme/blob/master/_config.yml#L39

**Comment by iskra0332** [comment]
Is it possible to add discord?

**Comment by jeromelachaud** [comment]
Sure, would you like to open a PR? :-)

**Comment by iskra0332** [comment]
Thank you for the speedy response! I would certainly like to do a pull request but I am sort of a newbie at this stuff so give me a bit to figure this out. Also in issue #44 or link https://github.com/jeromelachaud/freelancer-theme/issues/44 IgorPhelyp made the suggestion of updating the fot-awesome.min.css local file from this link https://maxcdn.bootstrapcdn.com/font-awesome/4.6.2/css/font-awesome.min.css.

It is version 4.6.2. Perhaps we could update the file altogether while we are at it. I updated to the 4.6.2 and it added the medium icon as requested in issue #44 but unfortunately discord had not been added. I have not figured out yet how to add the discord to it.

**Comment by iskra0332** [comment]
On Font Awesome's website, it requires you to use "pro" to get the discord icon. So not sure what kind of problems that causes.

**Comment by iskra0332** [comment]
I think I about have it figured out but my computer is about to die. I will do a pull request tonight updating it to 5.7.2 which includes meduim and discord along with many others.
