### ISSUE TITLE
changing navbar default background

### ISSUE THREAD

**Issue by cruznick** [jeromelachaud/freelancer-theme#7]
Hi i want to say thanks in advance and then ask where i can change this default color as i dont find where is it generated when building the site (the black rectangle around portfolio )
![2015-01-11 11_18_46-](https://cloud.githubusercontent.com/assets/460390/5696054/fdb1d180-9983-11e4-9709-8debca78ab2b.png)

**Comment by gauravparmar** [comment]
Use background-color CSS property for this.

**Comment by jeromelachaud** [comment]
This is inherited from bootstrap default style.
Up to you to override it in the main.css file.

**Comment by gauravparmar** [comment]
You can also create a custom CSS file and add all your customization CSS in
it and then include it in all the required pages after other CSS files to
override existing bootstrap CSS.
