### ISSUE TITLE
Font Awesome Icon Bug with Fix 

### ISSUE THREAD

**Issue by vidyagc** [jeromelachaud/freelancer-theme#79]
## Bug
The default overflow property for &lt;hr&gt; in some versions of Chrome, Edge and IE is hidden. This results in the following css not rendering properly - the Font Awesome star icon specified in 'content' in hr.star :after (content: "\f005") does not display.

## File 
_includes/css/main.css

## CSS
```
hr.star-light,
hr.star-primary {
    margin: 25px auto 30px;
    padding: 0;
    max-width: 250px;
    border: 0;
    border-top: solid 5px;
    text-align: center;
}

hr.star-light:after,
hr.star-primary:after {
    content: "\f005";
    display: inline-block;
    position: relative;
    top: -.8em;
    padding: 0 .25em;
    font-family: FontAwesome;
    font-size: 2em;
}
```

## Fix / Solution
To fix the above issue (have the FA star icon render in the header) specify the overflow property in hr.star CSS as 'visible'. 
```
hr.star-light,
hr.star-primary {
    margin: 25px auto 30px;
    padding: 0;
    max-width: 250px;
    border: 0;
    border-top: solid 5px;
    text-align: center;
/* Added overflow property and set to 'visible' */
    overflow: visible;
}
```

Best,
Vidya

**Comment by jeromelachaud** [comment]
👍
