### ISSUE TITLE
--- layout: default --- (Index.html Issue)

### ISSUE THREAD

**Issue by ConnorPlaysYT** [jeromelachaud/freelancer-theme#83]
I have just installed all of the files into the root of my Apache directory which is /var/www/html and then gone to my website http://walkersnetworks.co.uk then it returns this: --- layout: default ---
any ideas why?

**Comment by sirmnemonic** [comment]
The same, what is happening ?

**Comment by jeromelachaud** [comment]
Hey Guys, I can't reproduce with `jekyll 3.8.2`
