### ISSUE TITLE
Contact form no longer working

### ISSUE THREAD

**Issue by moctarjallo** [jeromelachaud/freelancer-theme#91]
Hi
I've downloaded this theme a while ago and everything was working perfectly including the contact form which did redirect to a certain site to send emails. 
But it is no longer working and gives the error i encountered with other themes before i used this one:

Sorry, it seems that my mail server is not responding. Please try again later!

How to fix it, or what is going on?
Thanks

**Comment by itopaloglu83** [comment]
Jekyll is a static site generator. So you need to use an external service for that kind of capability. 

The theme supports using [Formspree](https://formspree.io) by default. Their free layer would be enough for basic contact needs. All you have to do is signup with Formspree and create a form there. Every form have unique address associated with it. Here's what it looks like `https://formspree.io/xeqablel`. We're only concerned about the unique id here(`xeqablel`). Once you create a form just add the line below to your `_config.yml` file right after where it says `contact: static`.

```
# More stuff here...
contact: static
email: xeqablel
# Even more stuff here...
```
